server:
  port: 8043
spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8040/eureka
    register-with-eureka: true
    fetch-registry: true
zuul:
  routes:
    api-a:
      serviceId: service01
      path: /**
